### ISSUE TITLE
Do not load the WikiEditor when TinyMCE is enabled on a page

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#10]
This is more of a request. At this moment only the standard editor (not the **WikiEditor**) is prevented from loading when **TinyMCE** is enabled on a page. 

There already is the below code in **TinyMCE.hooks.php** so maybe this is a bug:
```php
public static function disableWikiEditor( $editPage ) {
		global $wgTinyMCEEnabled;

		if ( $wgTinyMCEEnabled ) {
			return false;
		}
		return true;
	}
```

Is it possible to also prevent the **WikiEditor** from loading when **TinyMCE** is enabled? 

Together with the `__NOTINYMCE__` switch it is then possible to combine both on the same wiki.

I think most people have the **WikiEditor** enabled and don't use the standard editor. It would be nice if they could fall back to the **WikiEditor** instead of the standard editor. You can not do this at the moment because both **TinyMCE** and the **WikiEditor** will load on pages where **TinyMCE** is enabled.

Now this happens when a site uses the **WikiEditor**:
![1](https://user-images.githubusercontent.com/6680027/38873075-3b062b6c-4255-11e8-84be-8ba8fa26c823.png)

**Comment by yaronkoren** [comment]
You need to modify the WikiEditor extension to get this to work - look for the file "WikiEditor-changes.patch", right in the /TinyMCE directory, to see the change that needs to be made. I'm trying to get them to add this code directly into the WikiEditor code, so that this patch won't be necessary, but haven't succeeded yet.

**Comment by jongfeli** [comment]
Hello Yaron, thanks for the remider I did see the patch when I started with **TinyMCE** but I forgot about it :-(

I did try to apply the patch but the code in `WikiEditor.hooks.php` looks different in the "current" **WikiEditor** version used now. The below code (including the patch) is not working.

```php
/**
	 * EditPage::showEditForm:initial hook
	 *
	 * Adds the modules to the edit form
	 *
	 * @param EditPage $editPage the current EditPage object.
	 * @param OutputPage $outputPage object.
	 * @return bool
	 */
	public static function editPageShowEditFormInitial( $editPage, $outputPage ) {
		if ( $editPage->contentModel !== CONTENT_MODEL_WIKITEXT ) {
			return true;
		}

		// Give other extensions a chance to disable WikiEditor for this page.
		if ( !Hooks::run( 'WikiEditorDisable', [ $editPage ] ) ) {
			return true;
		}

		// Add modules for enabled features
		foreach ( self::$features as $name => $feature ) {
			if ( !self::isEnabled( $name ) ) {
				continue;
			}
			if ( isset( $feature['stylemodules'] ) ) {
				$outputPage->addModuleStyles( $feature['stylemodules'] );
			}
			if ( isset( $feature['modules'] ) ) {
				$outputPage->addModules( $feature['modules'] );
			}
		}

		$article = $editPage->getArticle();
		$request = $article->getContext()->getRequest();
		// Don't run this if the request was posted - we don't want to log 'init' when the
		// user just pressed 'Show preview' or 'Show changes', or switched from VE keeping
		// changes.
```

**Comment by yaronkoren** [comment]
The modified WikiEditor code looks correct... looking through all the code now, it looks like TinyMCE might need to be included in LocalSettings.php before WikiEditor for this to work. Could you see if that's the case?

**Comment by jongfeli** [comment]
Yes, that fixes the problem in all MW versions (27, 29 & 30)

**Comment by yaronkoren** [comment]
Okay, I just modified TinyMCE, so that now TinyMCE and WikiEditor can be installed in either order, and they should still work together correctly. Could you please verify this?

**Comment by jongfeli** [comment]
Yes it works. Now it does not matter in which order they are loaded.  Could #9 also be related to this?

**Comment by yaronkoren** [comment]
Okay, great. I doubt it.
