### ISSUE TITLE
Links don't end up working

### ISSUE THREAD

**Issue by poVoq** [yaronkoren/TinyMCE#13]
With the master from just now (and one from yesterday) there is a problem with parsing links on my page.

In the editor everything looks fine (although the popup for entering the url etc. is really small and cramped... you can't really see the url and name you are typing), but when I click on save the link is not created but rather this is shown:
`<a class="link external mw-external-link mceNonEditable" title="http://url.com/" href="http://url.com/" data-mw-type="external_link" data-mw-wikitext="%5Bhttp://url.com/%2520http://urls.com/%5D">http://url.com/</a>`

Any idea why this is happening?

**Comment by duncan-crane** [comment]
Hi

Thanks for trying out this extension.   I'm sorry you are having problems.  I just downloaded the current master but wasn't able to reproduce this issue (although there was a problem with handling switches).

I only have a limited variety of environments here so it might be something to do with browser or mediawiki versions.?  Would you let me know what versions of software you are using?

Many thanks

Duncan

**Comment by poVoq** [comment]
I am using a recently installed MW1.30 and are accessing it via Firefox 59.0.2 on Linux. My server is running on a shared host with php7.1 and Apache (reverse-proxied through Nginx). The MediaWiki is running with the Pivot skin.

Thanks for the help.

**Comment by poVoq** [comment]
Checking the browser console I get the following error:
`ReferenceError: invalid assignment left-hand side[Weitere Informationen] plugin.js:703:15`

This comes a bit after:
`GET https://wiki.watsan.eu/extensions/TinyMCE/tinymce/plugins/mw_paste/plugin.js [HTTP/2.0 200 OK 0ms]`

**Comment by duncan-crane** [comment]
Hi

Great - now I see what's happening.  There is an error handling external links - or in fact two errors.  Unfortunately, I'm not able to fix these now but will try to over the next day or so.

Thanks for spotting this.

Duncan

**Comment by duncan-crane** [comment]
I've uploaded fixes to mw_wikicode and mw_links plugins which I hope address the two problems I spotted.  As mentioned in another issue, the mw_links code was fairly roughly hewn from an existing plugin and probably needs a rewrite.  Maybe next weekend if I can, but hopefully this makes it functional for now..

Duncan

**Comment by poVoq** [comment]
Yes that seems to work now, Thanks a lot!
But the open in new window option seems still broken.

**Comment by duncan-crane** [comment]
Ok will look into that.  I don't think I ever actually tried it myself so tanks for spotting it.

**Comment by poVoq** [comment]
While regular links are working fine now, I noticed that these recent changes broke my draw.io integration :(
Before it was no problem to insert links like this: {{#drawio:testing|type=png}} even through the custom macro + menu in the editor, but now these come out totally garbled.

**Comment by duncan-crane** [comment]
Hi, I'm very sorry you're having a problem with your draw.io integration.  I've been thinking about trying to integrate draw.io myself and I'd be very interested in any tips you have?
I tried this code using the '{ ; }' menu button which is for inserting parser functions, templates etc and it seems to work OK.  I then noticed you mention inserting links, so I wondered if you were trying to insert this code with the Link button which does indeed result in a garbled mess of code?
Clearly, the Link button ought to behave gracefully when given non-link code so I'll add that to the list of fixes.  
Would you let me know if you were using the Link button or '{ ; }' button.  If not the latter would you give it a try?
Many thanks, Duncan

**Comment by poVoq** [comment]
Selfhost draw.io ;) Just put the src directory from the draw.io repository somewhere on your webserver and change all the urls in the ext.drawioeditor.js file (from this https://github.com/mgeb/mediawiki-drawio-editor ) to point to your draw.io instance.

I am not sure I understand your point though with the editor buttons though.
I added as by your description this to the LocalSettings.php:
```
#TinyMCE custom macros
$wgTinyMCEMacros[] = array(
        'name' => 'Draw.io PNG',
        'image' => 'https://mydomain.com/images/tinymce/paint-brush.png',
        'text' => '{{#drawio:!INSERT_NAME_HERE!|type=png}}'
);
$wgTinyMCEMacros[] = array(
        'name' => 'Draw.io SVG',
        'image' => 'https://mydomain.com/images/tinymce/paint-brush.png',
        'text' => '{{#drawio:!INSERT_NAME_HERE!|type=svg}}'
);
$wgTinyMCEMacros[] = array(
        'name' => 'Draw.io Interactive',
        'image' => 'https://mydomain.com/images/tinymce/paint-brush.png',
        'text' => '{{#drawio:!INSERT_NAME_HERE!|interactive}}'
);
```
Previously this inserted `{{#drawio:INSERT_NAME_HERE|interactive}}` into the editor window and would safe fine. Now it looks like this:
![drawiotinly](https://user-images.githubusercontent.com/940360/39264824-1393bec4-48c6-11e8-9275-808c9d3f5a74.png)

Directly below the heading is a drawio link that was inserted via the edit-source option, which works fine but looks a bit strange in the editor on further edits as the image isn't shown.
The bigger problem however is what is below, e.g. this is what gets inserted through the plus button. It sort of works, but looks really strange, but you can't actually edit the name of the draw.io file anymore. And also somehow this ​ `<*****>` gets added to the page after saving, which I have no idea where it comes from.

So is is semi functional as you can manually clean it up again and choose the name by highlighting it before adding the draw.io link via the + menu, but maybe that could be improved? Thanks for looking into it.

**Comment by duncan-crane** [comment]
Hi there
Thanks for the draw.io tips.
I'd misunderstood that you were using the macro facility.  The presence of the <*******> suggests it may be connected with the changes I made last weekend.  This is used as a placeholder for wikitext during translation from HTML to wikicode and I may have overlooked one or more cases where this should happen.  Thanks for the further info which will help me isolate the problem, hopefully.
Duncan

**Comment by duncan-crane** [comment]
Hi
I think I have managed to fix the template problem now.  I haven't tried it with draw.io itself yet but I think it should work OK if it was working before.  If you have time would you see if you can reproduce the error when using the code I uploaded to the master branch today?
For the links opening in  a new window, I don't believe that this isn't a standard capability within mediawiki so I'm not sure what wikicode I could insert to achieve this.  I realised the target field was in the original TinyMCE plugin because, of course you can open links in new windows in HTML.  I wonder if I should just remove the target field from the dialog box, unless someone has a suggestion? @yaronkoren @poVoq @jongfeli what do you think?
Many thanks, Duncan

**Comment by poVoq** [comment]
Seems to work fine now, including the draw.io macros. Thanks a lot!

I guess if that isn't possible within Mediawiki, better to remove it. But a bit strange that this standard HTML function isn't available at all.
