### ISSUE TITLE
Problem with popups in Pivot skin (previously: Upload button in Links, but not in images)

### ISSUE THREAD

**Issue by poVoq** [yaronkoren/TinyMCE#14]
Hi,

I have this strange issue with the latest master that the image button doesn't have an local upload button in the popup but the url/link popup does.

Otherwise the editor seems to be more or less working, so this seems like a strange error.

Thanks for the help.

**Comment by duncan-crane** [comment]
Hi

That is strange.  The local upload button is hidden if the type of the upload is 'url' or 'file on this wiki'.  It will also be hidden if you had selected an image in the editor window before clicking the upload button.  In the latter case the button will be 'highlighted' to show that an image is selected.

Sometimes (for example if you tried to upload a file that is already in the wiki) depending on your response to the warning message, the upload wizard will be set for linking to a file on the wiki.

Hopefully one of these conditions will explain what you are seeing?

Many thanks

Duncan

**Comment by poVoq** [comment]
Sadly no, this happens always and even on a "virgin" wiki page.

**Comment by duncan-crane** [comment]
There's another possibility in that the local file button only shows if the user has permission to upload.  This is a longshot as I'm sure you'd know if you had that permission or not?

I'll do some more digging when I have a little more time.

Duncan

**Comment by poVoq** [comment]
No, this is with the sysop user that has full access rights.

Here is how strange the link menu looks:
![linkmenu](https://user-images.githubusercontent.com/940360/39120876-2385aa54-46f0-11e8-9ac7-8979b90fc637.png)

and this is the image menu without the upload button:
![imagemenu](https://user-images.githubusercontent.com/940360/39120886-2f0c2682-46f0-11e8-9515-8e0b0a43d330.png)

**Comment by duncan-crane** [comment]
That is strange!  I've never seen that before - it looks like it thinks its a mobile device.  I don't have firefox so I'll have to install to see if it does that for me.  May take a few days as I also have a day job :(

**Comment by poVoq** [comment]
Firefox is really recommended these days :) But I installed Chrome now to see if it was a browser issue, and it looks exactly the same there.

On Android Firefox it also looks like that (1080p screen). Maybe the Pivot theme is causing this?

**Comment by duncan-crane** [comment]
Ah now that's a possibility.  Are you able to try an alternative skin?  I use Vector.  If the two differ then it may be the way I'm sizing the popup windows.

**Comment by poVoq** [comment]
Tested it with the Vector skin, and it seems to be working fine there.

Any chance you could look into the issue with the pivot theme? It and the "foreground" skin are pretty popular and use the Zurb Foundation Framework.

Edit: With the Bootstrap3 based Tweeki & chameleon skin it also works fine.

**Comment by duncan-crane** [comment]
Hi, I can certainly look into this as I think I might be interested in using his skin too on some applications.  I do have a couple of other things to look at and I'm afraid I'm really just a weekend coder.  Would you let me know the priority of the different areas you'd like me to look at so I get to the more important ones first?
Many thanks, Duncan

**Comment by poVoq** [comment]
I guess the theme issue is lower priority as the Chameleopn theme is also nice and works fine with the popups. The link issues in the editor are more or a problem for now. Thanks for the support!

**Comment by Hutchy68** [comment]
I agree with @duncan-crane 

>it looks like it thinks its a mobile device. 

The question is why?
