### ISSUE TITLE
TinyMCE shows "old" page content

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#15]
In some cases when deleting the page content with the source editor (**WikiEditor**) and then reopening the page in **TinyMCE** the old page content is shown in **TinyMCE**. I can not reproduce this but it seems that some cases "the cash"  is not cleared immediately.  

Page content where this happened was:

```
[[File:20171109 172708.jpg|250px]]

<*****>
[[File:20171109 172708.jpg|100px]]
```

**Comment by duncan-crane** [comment]
Does look similar to the previous issue.  Would you let me have the wikicode you expected to see and/or a capture of the Tiny edit screen?

Many thanks

Duncan

**Comment by duncan-crane** [comment]
Hi Felipe
I'm hoping this will have been fixed by the changes I just added.  Would you give it a try and let me know?
Many thanks, Duncan

**Comment by duncan-crane** [comment]
Hi Felipe, I haven't been able to reproduce this problem so I'm closing it.  Please do reopen if you are still experiencing it.  Duncan
