### ISSUE TITLE
Option to turn off right-click menu?

### ISSUE THREAD

**Issue by poVoq** [yaronkoren/TinyMCE#16]
As nice as the custom right-click menu is, it prevents to selected a language and see spelling suggestions in the browser spellcheck (with Firefox). Maybe a button in TinyMCE to temporarily disable the right-click menu would help?

**Comment by duncan-crane** [comment]
I think it may be possible to have both show - I'll check it out.
Many thanks, Duncan

**Comment by duncan-crane** [comment]
Hi
I use the standard TinyMCE plugin to process the context menu.  The documentation claims that it should display along with the browser context menu as a default, but I couldn't get this to work in a sensible way.  However, I did notice if you right click outside the TinyMCE editor window, you do get the browser context context menu rather than TinyMCE's.  I thought this may better anyway, since their may be common commands that behave different depending on whether you are in the browser or TinyMCE context. What do you think @poVoq @yaronkoren @jongfeli?
Many thanks, Duncan

**Comment by poVoq** [comment]
The main point is to click inside, so that you can switch the language of the spell check and get the right-click menu for the spelling suggestions of the browser. I guess this is more important for a non-native english speaker like me, but still a quite vital feature of the browser. Yes there are some spell check plugins  for inside TinyMCE, but why not have a button that toggles the right click menu?

**Comment by duncan-crane** [comment]
Ah - of course that is a very good reason. Let me look into it further.

**Comment by duncan-crane** [comment]
Hi poVoq
Sorry it's taken a little while to investigate this properly and I'm a little embarrassed now that I have.  If you ctrl-right click then you get the browser menu.  This seems a very neet solution and one  the clever people at Ephox provide without any need for customisation.  Does this work for you?  I'll close this for now but do reopen if you wish?
Duncan

**Comment by poVoq** [comment]
Ah, I didn't know that. But maybe is is possible to fit a small notice into the rightclick menu to tell users about this?
Otherwise most users will never know...

**Comment by duncan-crane** [comment]
I have put a partial solution in the master branch.  This shows a button on the context menu to invoke the browser context menu and has tooltip text informing the user of the ctrl-right click behaviour.  I am still working to allow the user to click this button to also invoke the browser context menu.

**Comment by duncan-crane** [comment]
Hi @poVoq 
I finally got around to doing what you requested.  The button on the TinyMCE context menu now offers a 'confirm' box which allows you to switch-off the TinyMCE context menu.  I haven't yet figured out how to add an option on the browser menu to reactivate the TinyMCE context menu, hohum.  Any thoughts on how to do this would be very welcome.
Many thanks
Duncan

**Comment by duncan-crane** [comment]
Whoops - I realised I haven't yet added this to the distribution!!!  Should be coming soon:-)

**Comment by duncan-crane** [comment]
This has now been changed in the Git/Gerrit repository as described above

**Comment by poVoq** [comment]
Works great, thanks a lot!
