### ISSUE TITLE
External and Internal Links doesnt end up working

### ISSUE THREAD

**Issue by Skintex** [yaronkoren/TinyMCE#18]
Hi Duncan,

i hava a little problem.
Everytime i include a link on one of my Wikisites, he shows me it after i published it that way

It looks like this right now if i wanna use some links:

![grafik](https://user-images.githubusercontent.com/39126925/39819546-04da3406-53a4-11e8-9bb4-b8e3f68d75b3.png)

It seems it is similar to the #13 but i´m not sure.

I´m running MW1.30 and accesing it via Firefox 59.0.3 on Windows10. I also tried Microsoft Edge and IE, with the same result. On my Server i have php7.2.1 running and the wiki is right now running with no special skin.

Or did i missed something and i need to configure something else then to Load the Extension in the Localsettigns.php?

Would be cool if u could help me here.
Many thanks

Skintex

**Comment by duncan-crane** [comment]
Hi Skintex
Thanks for trying our extension.  I'll definitely have a look into your issue over the next day or so.  I think we've managed to solve most of these so I'm confident we should be able to sort this.  Can I ask when you last downloaded the TinyMCE extension as we've made quite a few updates recently?
Many thanks
Duncan

**Comment by duncan-crane** [comment]
Hi Skintex
I think I found the problem.  I failed to update one of the files when I made changes last weekend.  I've now uploaded a version of the file to the master branch which I hope fixes your problem.  Would you give it a try and let me know?
Many thanks
Duncan

**Comment by Skintex** [comment]
Hi Duncan
sure i try it next Monday when i´m back at work. Thanks so far for the help, i try it and give u a feeback.

**Comment by duncan-crane** [comment]
Closing subject to any further feedback from Skintex

**Comment by Skintex** [comment]
Hi Duncan,

just wanted to let u know i testet it yesterday. It works thank you for your help.
Many Thanks Skintex
