### ISSUE TITLE
Pasting in a table + bulleted list from Word leads to problems

### ISSUE THREAD

**Issue by yaronkoren** [yaronkoren/TinyMCE#20]
This is a bit obscure, but: if you have a simple table in Word (or LibreOffice - that's what I'm using), and a simple bulleted list right after that, and you paste them both into TinyMCE, the bulleted list gets stored as HTML, not wikitext. Also, going to view the wikisource leads to an "infinite loop", which I'm guessing is related.

Also, an extra ">" shows up before the table, which may or may not be related.

**Comment by duncan-crane** [comment]
HI Yaron
I was able to reproduce the problem but only intermittently.  However, I did notice a problem with list parsing that I fixed and this may have been causing the issue you've had. I've uploaded to the master branch.  If you are able to test this would you let me know if it has resolved the problem?
Many thanks, Duncan

**Comment by yaronkoren** [comment]
Yes, the main problem is fixed - that's great!

The only remaining issue is that I'm still seeing that ">" showing up before the table, which I assume is due to some parsing thing not fully removing the HTML. Do you see that too?

**Comment by duncan-crane** [comment]
Hi Yaron
Obscure maybe but it has surfaced a number of issues with regex replacements that could have caused similar problems, so thank you for your great detectoring :-)
I've uploaded what I hope is a fix.  Please do let me know if this solves the problem?
Duncan

**Comment by yaronkoren** [comment]
Hi Duncan - for me this change seems to make the parsing worse (especially of bulleted lists), but it could be due to browser caching. Does it work for you for bulleted lists?

**Comment by duncan-crane** [comment]
Hi Yaron - I've done quite a bit more testing with the bulleted lists, including nested lists and pasting nested lists into nested lists.  Appart from a couple of issues with pasting from Word, it seems to work for me, including round tripping and saving etc.  The issues I noticed with pasting were:
1) that pasting created a nested <div> structure and that only a single level of this was removed by the parser when translating back to wiki code.
2) bullets that are special characters in Word are pasted as characters at the start of the bulleted item (the bullet structure is however preserved).
I've added a change to recursively remove <div>s which I hope resolves 1). 
Item 2) is a little more complex as I don't think mediawiki supports alternative bullet characters?  It is possible to get Tiny to support them using the advlist plugin but that still leaves the question of translation to wikicode.  On balance I think the current behavior is reasonable?
I'm not sure if the fix resolves the problem you've experienced.  If not, would you let me have the code 'snippet' that's causing you problems so I can see if I can reproduce it?
Many thanks, Duncan

**Comment by yaronkoren** [comment]
Okay - the bulleted list problem is gone again (assuming it was actually a problem before). But I still get a ">" before the pasted-in table. I'm using the Chrome browser, and I should note that I'm pasting from LibreOffice Writer, not Word - maybe that's the issue. The thing I'm pasting in is just a 2x2 table, with the four cells filled in with "A", "B", "C" and "D" respectively. The table shows up fine, but there's a ">" above it - and it looks like every time I do a "round trip", it adds another ">" above it.

**Comment by duncan-crane** [comment]
Hi Yaron, I'm sorry this is still giving you problems.  I've uploaded a version of the mw_paste plugin that copies out the contents of the pasted text to the console before it gets processed in the mw_wikicode parser.  Would you try again with this code and let me know what it copies out to the console as this may give me some clues as t what's happening.  Many thanks - Duncan

**Comment by yaronkoren** [comment]
The problem is still happening with the latest mw_paste (maybe not surprising), but here's the output in the console:

```
<table width="100%" cellpadding="6" cellspacing="0">
	<col width="128*">
	<col width="128*">
	<tr valign="top">
		<td width="50%">
			<p>A</p>
		</td>
		<td width="50%">
			<p>B</p>
		</td>
	</tr>
	<tr valign="top">
		<td width="50%">
			<p>C</p>
		</td>
		<td width="50%">
			<p>D</p>
		</td>
	</tr>
</table>
```

That <col> tag looks suspicious... I just looked it up, and apparently it usually goes into a <colgroup> tag, but it doesn't have to. Maybe that's the cause of the issue, though?

**Comment by duncan-crane** [comment]
Hi Yaron
It's been a little hard to reproduce this error as I haven't any software that produces the <colgroup> and<col> tags, so I had to frig the code to be able to test my fix.  
Basically the mw_wikicode plugin should now strip out these tags in the same way it does for <thead>, <tbody> etc which mediawiki doesn't support [https://www.mediawiki.org/wiki/Help:Tables#Common_attributes_for_columns,_column_groups_and_row_groups](url).  
Because I could only test using a frig, would you retest for me and tell me if this now works for you?
Many thanks
Duncan

**Comment by yaronkoren** [comment]
Yay! No more extra brackets. The Word/LibreOffice-to-wikitext conversion seems to work great now - I don't see any issues.

**Comment by duncan-crane** [comment]
Fab :-)
