### ISSUE TITLE
Whoops!!!

### ISSUE THREAD

**Issue by duncan-crane** [yaronkoren/TinyMCE#22]
Hi @yaronkoren, @poVoq @jongfeli and @Skintex
I'm very sorry to say I inadvertently uploaded the wrong plugin.js file to mw_upload a couple of days ago.  This has caused me a number of problems with the TinyMCE extension behaving very erratically. I've now put this right and things seems to be working more reliably.
If you downloaded the code in the last couple of days you may also have encountered some strange behavior.  Please do download again and accept my apologies for any time I've wasted as a result of this error.
Many thanks
Duncan

**Comment by yaronkoren** [comment]
Okay - I'm out for most of the day, but I'll try it out when I get back. That'll be great if it works better!

**Comment by duncan-crane** [comment]
We've moved on ...
