### ISSUE TITLE
Drag-and-drop of "wikimagic" blocks leads to problems

### ISSUE THREAD

**Issue by yaronkoren** [yaronkoren/TinyMCE#23]
Hi,

There's some strange behavior involving those blocks that show up around external links, parser functions, etc. - if you click on one, and move the mouse, it sort of does a drag-and-drop but sort of doesn't - the wikitext gets copied to the new location, but it also stays in the old location, and the editing gets messed up - you basically have to refresh the page, or at least do a "round-trip" on the wikitext, to get editing working again normally.

I would think the best solution - at least the easiest - is to disable drag-and-drop entirely for these blocks. It doesn't seem that important to be able to move a link, parser function, etc. around on the page - this can be easily done with a cut-and-paste anyway.

What do you think?

-Yaron

**Comment by duncan-crane** [comment]
Hi Yaron
Fortunately this is a more general case of issue #8 which means I had a ready made solution to go without having to disable drag and drop.  If you have a chance to try it, would you let me know if this now works for you?
Duncan

**Comment by yaronkoren** [comment]
Oh wow! It works great now.

**Comment by duncan-crane** [comment]
Seems to be fixed :-)

**Comment by jongfeli** [comment]
It is.
