### ISSUE TITLE
IE11 Compatiblity

### ISSUE THREAD

**Issue by nelsonbt** [yaronkoren/TinyMCE#26]
Is there effort being put into maintaining IE11 compat?
We're encountering an issue with this JS code in the extension when run from IE11:

   /**
    * Event handler for "beforeSetContent"
    * This is used to process the wiki code into html.
    * @param {tinymce.ContentEvent} e
    */

   function _onBeforeSetContent(e) {
//debugger;
       // if raw format is requested, this is usually for internal issues like
       // undo/redo. So no additional processing should occur. Default is 'html'
       if (e.format == 'raw' ) {
           return;
       }
       e.format = 'raw';
       if (!e.load) e.content = _convertHtml2Wiki(e);
       if (e.content.startsWith('<dropsrc>')) {
           e.content = e.content.substring(9, e.content.length - 10);
           return;
       }
       e.content = _wiki2html(e);
       return e.content;
   }

IE complains: Object doesn't support property or method 'startsWith'

I've seen some hints that creating a polyfill for that member function could fix the issue.

**Comment by duncan-crane** [comment]
Hi @nelsonbt 
Firstly, thank you for trying out our extension and for investigating this issue.  I'm sorry this has happened as it was definitely working with IE11 until recently, so it's probably something I changed recently.  I should be able to look into it tomorrow, if you can wait that long?
Many thanks
Duncan

**Comment by nelsonbt** [comment]
@duncan-crane , Thanks for the fast response! 
I'm glad to hear that IE11 is still being given some effort. Tomorrow would be more than ok -- we're trying this extension out on a test server as we prep for an upgrade.
We're really hoping this extension will help with adoption in our group.

**Comment by duncan-crane** [comment]
Hi @nelsonbt 

I've now corrected these problems (IE11 js doesn't recognise .include, .startswith and .endswith string functions).  In future I'll try to remember to test on IE11 before releasing but do please let me know if you encounter any more issues.

By the way we are in the process of moving the code to the Mediawiki Git/Gerrit repository so at some point soon you will need to go there to get updates.  This will be available through the extension's home page.

Many thanks
Duncan

**Comment by nelsonbt** [comment]
@duncan-crane  Thanks! We've updated to master and it's working great.

**Comment by duncan-crane** [comment]
Now resolved
