### ISSUE TITLE
The None value for "Horizontal alignment" is not loaded from the page

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#6]
When selecting "None" (the picture should be shown inline) for the Horizontal alignment the picture is saved with None. If you then edit the page again the value for the Horizontal alignment is changed to "Left" in the UI.

In other words, all the values work but only the None parameter is not correctly loaded from the page when editing, it changes to Left.

**Comment by duncan-crane** [comment]
Hi Felipe

I've made quite a lot of changes to this functionality over the weekend (see issue #3). I hope this may have resolved this issue.  Please let me know if it does?

Many thanks
Duncan

**Comment by jongfeli** [comment]
Is fixed, you can now make any combination you want.
