### ISSUE TITLE
None parameter "Horizontal alignment" causes problems on existing pages

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#7]
It seems that because of #6 editing an existing page with pictures that are shown inline the None parameter is ignored.

What is on the page:
```
 ==Heading==
* Some text
[[File:20171109 172708.jpg|none|middle|thumb|20171109 172708.jpg]]
* Some other text
* And still some more text
```

What is shown in the editor:

![1](https://user-images.githubusercontent.com/6680027/38861750-987ceb4a-4233-11e8-8b21-d77294fd0b21.png)

-----------------------------------------------------------------------------------------------------------

What it should be:

![2](https://user-images.githubusercontent.com/6680027/38861877-dd20a2b4-4233-11e8-99c2-6d210ce03e47.png)

**Comment by duncan-crane** [comment]
Hi Felipe

I've made quite a lot of changes to this functionality over the weekend (see issue #3). I think this should have resolved this issue. Please do let me know if it is still occurring for you?

Many thanks
Duncan

**Comment by jongfeli** [comment]
Hello Duncan, the **None** issue seems to be fixed but under **MW-1.30** the following can happen. When the below syntax is on a page:

```
==Heading==
* Some text
* Some other text
[[File:20171109 172708.jpg|none|middle|thumb|20171109 172708.jpg]]
* Text text
* dsfdsfsfsf
```

If you then edit the page with **TinyMCE** 

It looks like this in the editor field and source code window:
![1](https://user-images.githubusercontent.com/6680027/39120441-bd17c078-46ee-11e8-9f86-8dc9ba7a4b44.png)

If you then save it (no changes) you end up with:

```
==Heading==
* Some text
* Some other text
[[File:20171109 172708.jpg|none|middle|thumb|20171109 172708.jpg]]
```

All the text below the picture is gone. This only happens under MW-1.30 and seems to be related to the **Linebreak** either before the picture or after the picture.

**Comment by duncan-crane** [comment]
Hi Felipe

That's great the none issue is fixed.  I currently don't have a mw 1.30 environment and the problem doesn't occur with 1.27 LTS which I do use.  I think you are probably right about the Linebreak but I will have to get a mw 1.30 set up which I probably won't be able to do for a few days, if you would bear with me?

**Comment by jongfeli** [comment]
No problem.

**Comment by duncan-crane** [comment]
Hi Felipe
The code I just uploaded should have fixed this issue.  Would you mind trying it and letting me know if it works for you?
Many thanks, Duncan

**Comment by jongfeli** [comment]
It works.
