### ISSUE TITLE
Grabbing and moving pictures results in HTML on the page

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#8]
When grabbing a picture with the mouse pointer and moving it to another place on the page injects  HTML on the page.

Moving the below picture from below **Heading No 1** to below **Heading No 2**:

![1](https://user-images.githubusercontent.com/6680027/38866520-6b51ce84-4241-11e8-93f2-f9fd48c62c46.png)

----------------

The result after the move is:

![2](https://user-images.githubusercontent.com/6680027/38866539-796f0856-4241-11e8-938c-7f7b14df4b8a.png)

**Comment by duncan-crane** [comment]
This should now be fixed

**Comment by jongfeli** [comment]
It is.
