### ISSUE TITLE
TinyMCE not loading reliable in a form on MW 1.27.4 & 1.29.2 

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#9]
Unless I am doing something wrong it seems that the **TinyMCE** editor is not always loading when used in a form. It is working (loading) fine when not used in a form. 

The form:
```
<includeonly>
{{{info|query form at top|onlyinclude free text}}}
{{{for template|Test}}}
Fill in the remark: {{{field|remark|input type=textarea|rows=5|editor=tinymce}}}
{{{end template}}}
{{{standard input|free text|input type=textarea|rows=30|editor=tinymce}}}
{{{standard input|summary}}}
{{{standard input|minor edit}}} {{{standard input|watch}}}
{{{standard input|save}}} {{{standard input|preview}}} {{{standard input|changes}}} {{{standard input|cancel}}}
</includeonly>
```

## MW 1.27.4
After pressing Edit the form is loaded whiteout **TinyMCE** enabled. The only way to get **TineMCE** working is to reload the page with "CTRL F5" then it will load every time.

## MW 1.29.2
No matter what you do the **TinyMCE** editor is not loaded in a form. You see it pop up a fraction of a second but it disappears immediately.

## MW 1.30.0
It just works, no problems.

Please let me know when specific info is needed to diagnose this problem.

**Comment by jongfeli** [comment]
Small update the way it is in Master **2879b49**.

## MW 1.27.4
**TinyMCE** in a form is broken. When pressing **Edit**, only the `Fill in the remark:` field is showing:

![1](https://user-images.githubusercontent.com/6680027/39123191-6347bb44-46f7-11e8-8170-240057334c9f.png)

Reload the page with "CTRL F5" does **NOT** load **TinyMCE**:

![2](https://user-images.githubusercontent.com/6680027/39123202-718b243e-46f7-11e8-8382-46c1bd5d2b4c.png)

## MW 1.29.2
No matter what you do the **TinyMCE** editor is not loaded in a form. It always looks like this:

![2](https://user-images.githubusercontent.com/6680027/39123202-718b243e-46f7-11e8-8382-46c1bd5d2b4c.png)

## MW 1.30.0
No change it works, no problems.

**Comment by duncan-crane** [comment]
Yaron has fixed this through a new version of Page Forms

**Comment by jongfeli** [comment]
It works just fine now.
